/**
 * Schnorr Signature Implementation using @aztec/bb.js (Grumpkin)
 * 
 * Sign: (R, s) where R = k*G, s = k + e * sk (mod Fq)
 * Verify: Not fully implemented in JS (requires arbitrary point arithmetic)
 */

import { Barretenberg, Fr } from '@aztec/bb.js';
import type { Point, SchnorrSignature } from './types.js';
import { poseidonHash } from './poseidon.js';

// Grumpkin Scalar Field (BN254 Base Field)
// This is the order of the group generated by pedersenCommit
export const GRUMPKIN_SCALAR_MODULUS = 21888242871839275222246405745257275088696311157297823662689037894645226208583n;

let bb: Barretenberg | null = null;

async function getBb(): Promise<Barretenberg> {
  if (!bb) {
    bb = await Barretenberg.new({ threads: 1 });
  }
  return bb;
}

/**
 * Validate a scalar is in the valid range for Grumpkin scalar field [0, Fq)
 */
function validateScalar(value: bigint, name: string): void {
  if (value < 0n) {
    throw new Error(`${name} must be non-negative`);
  }
  if (value >= GRUMPKIN_SCALAR_MODULUS) {
    throw new Error(`${name} must be less than Grumpkin scalar modulus`);
  }
}

/**
 * Generate a keypair for Schnorr signing
 */
export async function generateKeypair(): Promise<{ secretKey: bigint; publicKey: Point }> {
  // Secret key must be in Fq (Grumpkin scalar field)
  // Our utils.randomFieldElement gives simple random bytes mod Fr (BN254 scalar).
  // We need random mod Fq.

  // Custom random generation for Fq
  const secretKey = randomGrumpkinScalar();

  const publicKey = await derivePublicKey(secretKey);

  return {
    secretKey,
    publicKey,
  };
}

/**
 * Derive public key from secret key
 * pk = sk * G
 */
export async function derivePublicKey(secretKey: bigint): Promise<Point> {
  validateScalar(secretKey, 'secretKey');
  const backend = await getBb();

  // pedersenCommit([s], 0) computes s * G + 0 * H = s * G
  // Input Fr(s) - bb.js wraps this into the scalar mul
  // Note: Fr constructor handles bigints.
  // Although we are doing Grumpkin mul, standard pedersen uses Fr as input wrapper type?
  // Let's check debug_crypto.mjs which worked: `new Fr(BigInt(s))`
  const comm = await backend.pedersenCommit([new Fr(secretKey), new Fr(0n)], 0);

  return {
    x: frToBigInt(comm.x),
    y: frToBigInt(comm.y),
  };
}

/**
 * Sign a message using Schnorr signature
 * 
 * @param secretKey - Signer's secret key
 * @param message - Message to sign (as field element, usually hash)
 * @returns Schnorr signature (R, s)
 */
export async function schnorrSign(secretKey: bigint, message: bigint): Promise<SchnorrSignature> {
  // Validate inputs
  validateScalar(secretKey, 'secretKey');
  // Message is likely in Fr (BN254 scalar), but it's just bits for the hash.
  // We don't strictly validate message < Fq, but usually it is from Poseidon (Fr).

  if (secretKey === 0n) {
    throw new Error('secretKey cannot be zero');
  }

  const backend = await getBb();

  // Generate random nonce k mod Fq
  const k = randomGrumpkinScalar();

  // R = k * G
  const commR = await backend.pedersenCommit([new Fr(k), new Fr(0n)], 0);
  const Rx = frToBigInt(commR.x);
  const Ry = frToBigInt(commR.y);

  // Derive public key for hash
  // We can re-derive or expect it passed? Implementation signature is just (sk, m).
  // We must re-derive to be safe (or optimization: assume sk is valid)
  // Optimization: usually signing doesn't re-derive PK if not needed, but we ned it for 'e'.
  // If performance is an issue, we should change signature to take PK.
  const pk = await derivePublicKey(secretKey);

  // e = H(R || pk || m) using Poseidon (which uses standard BN254 Fr)
  // Note: Inputs to Poseidon are Fields (Fr). R.x, R.y, pk.x, pk.y are in Fr (Grumpkin coords).
  // message is in Fr.
  const e = poseidonHash([Rx, Ry, pk.x, pk.y, message]);

  // s = k + e * sk (mod Fq)
  // Calculate e * sk first. e is < Fr. sk is < Fq.
  // We do math in standard BigInt then reduce mod Fq.
  const s = (k + e * secretKey) % GRUMPKIN_SCALAR_MODULUS;

  return {
    r: { x: Rx, y: Ry },
    s,
  };
}

/**
 * Verify a Schnorr signature
 * 
 * NOTE: This is NOT implemented in TS/bb.js efficiently yet because specific point addition
 * is not exposed in the high-level bb.js API.
 * 
 * Returns true mostly as a placeholder or throws. 
 * Since this function is not critical for the server (which uses ZK proofs), we stub it.
 */
export async function schnorrVerify(
  publicKey: Point,
  message: bigint,
  signature: SchnorrSignature
): Promise<boolean> {
  // Cannot verify in JS without arbitrary point multiplication.
  // bb.js pedersenCommit only does scalars * generators.
  throw new Error("schnorrVerify is not implemented in JS. Verification must be performed via the Noir circuit.");
}

// Helper: Convert bb.js Fr to BigInt
function frToBigInt(fr: { value: Uint8Array }): bigint {
  let result = 0n;
  for (const byte of fr.value) {
    result = (result << 8n) | BigInt(byte);
  }
  return result;
}

/**
 * Generate a random scalar in the Grumpkin scalar field.
 * 
 * Uses 64 bytes (512 bits) of randomness reduced modulo the ~254-bit scalar modulus.
 * 
 * NOTE: This introduces a negligible bias (approx 2^-258), which is acceptable
 * for this use case. A uniform rejection sampling approach would be strictly
 * correct but this reduction is standard practice for field elements.
 */
function randomGrumpkinScalar(): bigint {
  const bytes = new Uint8Array(64);
  crypto.getRandomValues(bytes);
  let value = 0n;
  for (const byte of bytes) {
    value = (value << 8n) | BigInt(byte);
  }
  return value % GRUMPKIN_SCALAR_MODULUS;
}
