#!/usr/bin/env node
/**
 * Generate valid Prover.toml test data for the x402_zk_credential circuit.
 * Uses the fixed @demo/crypto package (Grumpkin/BN254 friendly).
 * Note: Grumpkin is a curve defined over the scalar field of BN254.
 */

import {
  pedersenCommit,
  generateKeypair,
  schnorrSign,
  poseidonHash7,
  initPedersen
} from '@demo/crypto';

// Test values
const nullifierSeed = 12345n;
const blindingFactor = 67890n;

// Service/context values
const serviceId = 1n;
const currentTime = BigInt(Math.floor(Date.now() / 1000));
const originId = 12345n;

// Credential values
const credTier = 1n;
const credPresentationBudget = 1000n;
const credIssuedAt = currentTime - 1000n;  // Issued 1000s ago
const credExpiresAt = currentTime + 86400n; // Expires in 1 day

// Presentation context
const presentationIndex = 0n;

async function main() {
  await initPedersen();

  // 1. Generate Issuer Keys
  console.error('Generating issuer keys...');
  const { secretKey, publicKey } = await generateKeypair();

  // 2. Compute the Pedersen commitment
  console.error('Computing commitment...');
  const commitment = await pedersenCommit(nullifierSeed, blindingFactor);

  // 3. Compute message hash (matches circuit logic)
  const message = poseidonHash7(
    serviceId,
    credTier,
    credPresentationBudget,
    credIssuedAt,
    credExpiresAt,
    commitment.point.x,
    commitment.point.y
  );

  // 4. Sign the credential
  const signature = await schnorrSign(secretKey, message);

  // Split s into 128-bit limbs
  const s = signature.s;
  const s_lo = s & ((1n << 128n) - 1n);
  const s_hi = s >> 128n;

  // Output Prover.toml content
  console.log(`# Generated by generate-test-data.mjs at ${new Date().toISOString()}`);
  console.log('');
  console.log('# Public inputs');
  console.log(`service_id = "${serviceId}"`);
  console.log(`current_time = "${currentTime}"`);
  console.log(`origin_id = "${originId}"`);
  console.log(`facilitator_pubkey_x = "${publicKey.x}"`);
  console.log(`facilitator_pubkey_y = "${publicKey.y}"`);
  console.log('');
  console.log('# Private inputs: Credential');
  console.log(`cred_service_id = "${serviceId}"`);
  console.log(`cred_tier = "${credTier}"`);
  console.log(`cred_presentation_budget = "${credPresentationBudget}"`);
  console.log(`cred_issued_at = "${credIssuedAt}"`);
  console.log(`cred_expires_at = "${credExpiresAt}"`);
  console.log(`cred_commitment_x = "${commitment.point.x}"`);
  console.log(`cred_commitment_y = "${commitment.point.y}"`);
  console.log('');
  console.log('# Private inputs: Signature');
  console.log(`sig_r_x = "${signature.r.x}"`);
  console.log(`sig_r_y = "${signature.r.y}"`);
  console.log(`sig_s_lo = "${s_lo}"`);
  console.log(`sig_s_hi = "${s_hi}"`);
  console.log('');
  console.log('# Private inputs: User secrets');
  console.log(`nullifier_seed = "${nullifierSeed}"`);
  console.log(`blinding_factor = "${blindingFactor}"`);
  console.log('');
  console.log('# Private inputs: Presentation context');
  console.log(`presentation_index = "${presentationIndex}"`);
}

main().catch(console.error);
